// Copyright 2026 AiCode Contributors
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <string>
#include <vector>
#include <cstdint>

namespace aicode {

/// Rarity tiers
enum class Rarity {
    Common = 0,      // 60%
    Uncommon = 1,    // 25%
    Rare = 2,        // 10%
    Epic = 3,        // 4%
    Legendary = 4    // 1%
};

/// Species - 18 types
enum class Species {
    Duck = 0,
    Goose = 1,
    Blob = 2,
    Cat = 3,
    Dragon = 4,
    Octopus = 5,
    Owl = 6,
    Penguin = 7,
    Turtle = 8,
    Snail = 9,
    Ghost = 10,
    Axolotl = 11,
    Capybara = 12,
    Cactus = 13,
    Robot = 14,
    Rabbit = 15,
    Mushroom = 16,
    Chonk = 17
};

/// Eye styles
enum class Eye {
    Dot = 0,      // *
    Sparkle = 1,  // +
    X = 2,        // x
    Circle = 3,   // o
    At = 4,       // @
    Degree = 5    // .
};

/// Hat types
enum class Hat {
    None = 0,
    Crown = 1,
    Tophat = 2,
    Propeller = 3,
    Halo = 4,
    Wizard = 5,
    Beanie = 6,
    Tinyduck = 7
};

/// Stat names
enum class StatType {
    Debugging = 0,
    Patience = 1,
    Chaos = 2,
    Wisdom = 3,
    Snark = 4
};

/// Companion data structure
struct Companion {
    // Bones - deterministic from user ID hash
    Rarity rarity = Rarity::Common;
    Species species = Species::Duck;
    Eye eye = Eye::Dot;
    Hat hat = Hat::None;
    bool shiny = false;  // 1% chance

    // Stats (0-100)
    int debugging = 50;
    int patience = 50;
    int chaos = 50;
    int wisdom = 50;
    int snark = 50;

    // Soul - generated by LLM, persisted
    std::string name;
    std::string personality;

    // Metadata
    int64_t hatched_at = 0;  // Unix timestamp
};

/// Utility functions
class BuddyUtils {
public:
    /// Get species name as string
    static std::string GetSpeciesName(Species species);

    /// Get rarity name as string
    static std::string GetRarityName(Rarity rarity);

    /// Get eye character (ASCII safe)
    static char GetEyeChar(Eye eye);

    /// Get hat ASCII art (line 0 of sprite, 12 chars wide)
    static std::string GetHatLine(Hat hat);

    /// Get rarity stars
    static std::string GetRarityStars(Rarity rarity);

    /// Get rarity color name (for terminal display)
    static std::string GetRarityColor(Rarity rarity);
};

}  // namespace aicode
